spring.application.name=demo

server.port=8080
management.server.port=8081

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=${spring.application.name}
info.app.version=@project.version@
info.app.description=Photo Service
