apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: photo-service
    includeSelectors: true

images:
  - name: docker.io/lazycomputing/photo-service
    newName: docker.io/lazycomputing/photo-service
    newTag: latest
