name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: ls -la
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify -DskipTests
      - run: mkdir staging && cp target/*.jar staging
      - run: cp ./Dockerfile staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
  publish:
    name: Create docker image and push to Docker Hub
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Package
      - run: ls -la
      - run: ls -la staging
