apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "photo-service.fullname" . }}
  labels:
    {{- include "photo-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "photo-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "photo-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.ports.service }}
              name: service
            - containerPort: {{ .Values.service.ports.management }}
              name: management
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: {{ .Values.restartPolicy }}
