apiVersion: v1
kind: Service
metadata:
  name: {{ include "photo-service.fullname" . }}
  labels:
    {{- include "photo-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "photo-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: service
      protocol: TCP
      port: {{ .Values.service.ports.service }}
      targetPort: service
    - name: management
      protocol: TCP
      port: {{ .Values.service.ports.management }}
      targetPort: management
